# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Build

on:
  pull_request:
  workflow_dispatch: # Allow running manually from web UI

jobs:
  package:
    name: Maven Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        # --batch-mode: Disable interactive input, making logs cleaner for CI.
        # -show-version: Print Maven and JDK version info.
        # --update-snapshots: Force update of snapshot dependencies.
        # --errors: Show full error stack traces on failure.
        # -DskipTests: Skip running tests. They should be run locally with custom credentials, see CONTRIBUTING.md.
        run: ./mvnw --batch-mode -show-version --update-snapshots --errors package -DskipTests
